### ISSUE TITLE
Detecting or preventing running loop confusion

### ISSUE THREAD

**Issue by mikeshardmind** [Rapptz/asqlite#9]
After a particular attempt at helping someone over in the discord.py server where I noticed what was essentially

```py
# global scoped
conn = asyncio.run_until_complete(asqlite.connect(...))
client = ...

# lots of other stuff which references conn in definitions, but doesn't run yet

# other library's code creating a new event loop and running all the stuff defined above.
client.run(...)
```

Suffice to say, this caused an issue for the user.

Not sure what the most elegant solution here would be. 

Obviously, requiring use as a context manager solves it, but that has some ergonomic changes that may be a non-starter for some people.

Could check the event loop vs the running loop, but this requires a threading lock if done from the thread side: (see the global threading lock where asyncio compares event loops across threads introduced as part of: https://github.com/python/cpython/issues/86558), which would add a non-insignificant overhead.

Could also just document this as a misuse, favoring ergonomics and performance in this case.

**Comment by Rapptz** [comment]
Checking every call is kind of a non-starter yeah. Realistically this "issue" would happen with any asyncio program so this isn't really worth documenting here either since it's just part of general knowledge. Otherwise every asyncio library would need to have a blurb on this. Hopefully this issue isn't really that widespread, but who knows.
